import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import {
  ArrowDown, ArrowLeft, ArrowUp, Bell, Bookmark, BookmarkCheck, Check, ChevronDown, CircleHelp,
  Clock3, Compass, ExternalLink, FileText, Flame, Home, Image as ImageIcon, Info,
  LayoutGrid, Link2, ListFilter, LoaderCircle, Menu, MessageCircle, Moon, MoreHorizontal, PenLine,
  Plus, RefreshCw, Search, Send, Settings, Share2, ShieldCheck, Sparkles, Sun, TrendingUp, Trophy,
  TriangleAlert, User, Users, Wand2, Wifi, WifiOff, X
} from 'lucide-react';
import { communities as builtinCommunities, currentUser, seedPosts } from './data';
import {
  createCommunity, generateBatch, generateHomeBatch, getContextSync, isStale, loadContext,
  registry, resetLedger, sortPosts, type CreateStage,
} from './services/simulation';
import { ContextUnavailableError, getCustomProxy, looksLikeSubreddit, normalizeSubredditName, searchSubreddits, setCustomProxy, type SubredditSuggestion } from './services/redditContext';
import { DEFAULT_MODELS, loadModelSettings, modelIsConfigured, saveModelSettings } from './services/llmClient';
import type { Comment, CommunityProfile, CultureProfile, ModelProvider, ModelSettings, Page, Post, SortOption, VoteState } from './types';
import './styles.css';

const sortOptions: { name: SortOption; icon: ReactNode }[] = [
  { name: 'Best', icon: <Sparkles size={16} /> },
  { name: 'Hot', icon: <Flame size={16} /> },
  { name: 'New', icon: <Clock3 size={16} /> },
  { name: 'Top', icon: <Trophy size={16} /> },
  { name: 'Rising', icon: <TrendingUp size={16} /> },
];

const POPULAR_SUBS = ['Deltarune', 'AskReddit', 'EldenRing', 'webdev', 'Cooking', 'formula1', 'StardewValley', 'mildlyinfuriating', 'BaldursGate3', 'ExperiencedDevs', 'todayilearned', 'anime'];

const formatCount = (value: number) => value >= 1_000_000
  ? `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1)}m`
  : value >= 1000 ? `${(value / 1000).toFixed(value >= 100_000 ? 0 : 1)}k` : value.toString();

const relativeAge = (timestamp: number) => {
  const minutes = Math.round((Date.now() - timestamp) / 60000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
};

const fallbackCommunity = (id: string): CommunityProfile => ({
  id,
  name: `r/${id}`,
  displayName: id,
  icon: (id[0] || 'r').toUpperCase(),
  color: '#5b5bd6',
  colorSoft: '#eeedff',
  category: 'Community',
  description: 'Simulated community',
  members: 0,
  online: 0,
  created: 'now',
  subscribed: false,
  rules: [],
  tone: '',
  vocabulary: [],
  typicalUsers: '',
  commonTopics: [],
  preferredFormats: [],
  typicalLength: '',
  commentStyle: '',
  commonOpinions: [],
  recurringThemes: [],
  contentToAvoid: [],
  moderationStyle: '',
});

/* ------------------------------------------------------------------ */
/* Primitives                                                          */
/* ------------------------------------------------------------------ */

function Brand({ compact = false }: { compact?: boolean }) {
  return (
    <div className="brand" aria-label="Fora home">
      <span className="brand-mark"><span className="brand-orbit" /></span>
      {!compact && <span className="brand-word">fora</span>}
    </div>
  );
}

function CommunityAvatar({ community, size = 'md' }: { community: CommunityProfile; size?: 'sm' | 'md' | 'lg' | 'xl' }) {
  return (
    <span className={`community-avatar avatar-${size}`} style={{ background: community.colorSoft, color: community.color }}>
      {community.icon}
    </span>
  );
}

function UserAvatar({ initials, size = 'md', online = false }: { initials: string; size?: 'sm' | 'md' | 'lg'; online?: boolean }) {
  return <span className={`user-avatar avatar-${size}`}>{initials}{online && <i className="online-dot" />}</span>;
}

function RichBody({ text, compact = false }: { text: string; compact?: boolean }) {
  const lines = text.split('\n').filter((line, i, array) => line.trim() || (i > 0 && array[i - 1].trim()));
  return (
    <div className={compact ? 'post-body post-body-clamp' : 'post-body'}>
      {lines.map((line, lineIndex) => {
        const pieces = line.split(/(\*\*[^*]+\*\*)/g);
        return <p key={lineIndex}>{pieces.map((piece, i) => piece.startsWith('**') ? <strong key={i}>{piece.slice(2, -2)}</strong> : piece)}</p>;
      })}
    </div>
  );
}

function AiPill({ generator }: { generator?: Post['generator'] }) {
  if (generator === 'you') return <span className="ai-pill you-pill">You</span>;
  return (
    <span className="ai-pill" title="Simulated post — generated by Fora, not a real Reddit post or user">
      <Wand2 size={11} /> AI
    </span>
  );
}

function ContextBadge({ profile, refreshing }: { profile?: CultureProfile; refreshing?: boolean }) {
  if (!profile) return <span className="context-badge loading"><LoaderCircle size={12} className="spin" /> reading r/…</span>;
  if (refreshing) return <span className="context-badge loading"><LoaderCircle size={12} className="spin" /> syncing</span>;
  if (profile.source === 'live' && !isStale(profile)) {
    return <span className="context-badge live"><Wifi size={12} /> Live context · {relativeAge(profile.fetchedAt)}</span>;
  }
  if (profile.source === 'live' || profile.source === 'cached') {
    return <span className="context-badge cached"><Clock3 size={12} /> Cached context · {relativeAge(profile.fetchedAt)}</span>;
  }
  if (profile.source === 'builtin') return <span className="context-badge offline"><WifiOff size={12} /> Built-in profile</span>;
  return <span className="context-badge offline"><WifiOff size={12} /> Estimated profile</span>;
}

function ConceptCard({ post }: { post: Post }) {
  if (!post.concept) return null;
  return (
    <figure className="concept-card">
      <figcaption className="concept-head"><ImageIcon size={14} /> {post.concept.format}</figcaption>
      <p className="concept-setup">{post.concept.setup}</p>
      {post.concept.punchline && <p className="concept-punch">{post.concept.punchline}</p>}
      <span className="concept-note">Described image concept — no image was generated</span>
    </figure>
  );
}

/* ------------------------------------------------------------------ */
/* Chrome                                                              */
/* ------------------------------------------------------------------ */

function Header({
  page, navigate, onCreate, theme, setTheme, sidebarOpen, setSidebarOpen, notify, communities, onSimulate,
}: {
  page: Page; navigate: (page: Page) => void; onCreate: () => void; theme: string; setTheme: (value: 'light' | 'dark') => void;
  sidebarOpen: boolean; setSidebarOpen: (value: boolean) => void; notify: (message: string) => void;
  communities: CommunityProfile[]; onSimulate: (name: string) => void;
}) {
  const [query, setQuery] = useState(page.type === 'search' ? page.query : '');
  const [focused, setFocused] = useState(false);
  const [remote, setRemote] = useState<SubredditSuggestion[]>([]);
  const [notificationsOpen, setNotificationsOpen] = useState(false);

  useEffect(() => {
    if (page.type === 'search') setQuery(page.query);
  }, [page]);

  useEffect(() => {
    const term = query.trim();
    if (term.length < 2 || !focused) {
      setRemote([]);
      return;
    }
    let active = true;
    const timer = window.setTimeout(() => {
      searchSubreddits(term, 6).then(results => {
        if (active) setRemote(results);
      });
    }, 320);
    return () => { active = false; window.clearTimeout(timer); };
  }, [query, focused]);

  const localMatches = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) return [];
    return communities.filter(c => c.name.toLowerCase().includes(term) || c.displayName.toLowerCase().includes(term)).slice(0, 4);
  }, [query, communities]);

  const slug = normalizeSubredditName(query);
  const canSimulate = looksLikeSubreddit(query) && !communities.some(c => c.id === slug.toLowerCase());

  const submitSearch = (event: FormEvent) => {
    event.preventDefault();
    const term = query.trim();
    if (!term) return;
    setFocused(false);
    (document.activeElement as HTMLElement)?.blur();
    if (looksLikeSubreddit(term)) onSimulate(term);
    else navigate({ type: 'search', query: term });
  };

  return (
    <header className="topbar">
      <div className="topbar-inner">
        <button className="icon-button mobile-menu" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Open navigation"><Menu size={22} /></button>
        <button className="brand-button" onClick={() => navigate({ type: 'home' })}><Brand /></button>
        <form className="searchbar" onSubmit={submitSearch} role="search">
          <Search size={19} />
          <input
            value={query}
            onChange={event => setQuery(event.target.value)}
            onFocus={() => setFocused(true)}
            onBlur={() => window.setTimeout(() => setFocused(false), 180)}
            placeholder="Search any subreddit — it gets simulated instantly"
            aria-label="Search subreddits"
          />
          <kbd>⌘ K</kbd>
          {focused && query.trim().length > 1 && (
            <div className="search-suggest">
              {canSimulate && (
                <button type="button" className="suggest-create" onMouseDown={() => onSimulate(query)}>
                  <span className="suggest-icon"><Wand2 size={16} /></span>
                  <span><b>Simulate r/{slug}</b><small>Read the real subreddit, then generate an original feed</small></span>
                </button>
              )}
              {localMatches.map(community => (
                <button type="button" key={community.id} onMouseDown={() => navigate({ type: 'community', id: community.id })}>
                  <CommunityAvatar community={community} size="sm" />
                  <span><b>{community.name}</b><small>In your simulation · {formatCount(community.members)} members</small></span>
                </button>
              ))}
              {remote.filter(item => !communities.some(c => c.id === item.name.toLowerCase())).slice(0, 4).map(item => (
                <button type="button" key={item.name} onMouseDown={() => onSimulate(item.name)}>
                  <span className="suggest-icon plain">r/</span>
                  <span><b>{item.displayName}</b><small>{formatCount(item.subscribers)} members on Reddit · not simulated yet</small></span>
                </button>
              ))}
              <button type="button" className="suggest-plain" onMouseDown={() => navigate({ type: 'search', query: query.trim() })}>
                <Search size={15} /> Search posts for “{query.trim()}”
              </button>
            </div>
          )}
        </form>
        <div className="top-actions">
          <button className="icon-button theme-toggle" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label="Toggle theme">
            {theme === 'light' ? <Moon size={19} /> : <Sun size={19} />}
          </button>
          <div className="popover-wrap">
            <button className="icon-button has-indicator" onClick={() => setNotificationsOpen(!notificationsOpen)} aria-label="Notifications">
              <Bell size={20} /><span className="notification-dot" />
            </button>
            {notificationsOpen && (
              <div className="popover notifications-popover">
                <div className="popover-head"><div><h3>Notifications</h3><span>Simulated activity</span></div><button className="text-button" onClick={() => { notify('Marked as read'); setNotificationsOpen(false); }}>Mark all read</button></div>
                <button className="notification-row" onClick={() => { navigate({ type: 'explore' }); setNotificationsOpen(false); }}>
                  <span className="notification-icon trend"><TrendingUp size={17} /></span><span>New topics detected in your simulated communities<small>Context refreshes about every 40 minutes</small></span>
                </button>
                <button className="notification-row read" onClick={() => { navigate({ type: 'settings' }); setNotificationsOpen(false); }}>
                  <span className="notification-icon reply"><Wand2 size={17} /></span><span>Connect a model for richer generation<small>Optional — the built-in engine works without one</small></span>
                </button>
              </div>
            )}
          </div>
          <button className="create-button" onClick={onCreate}><Plus size={18} /><span>Create</span></button>
          <button className="profile-button" onClick={() => navigate({ type: 'profile' })} aria-label="Open profile"><UserAvatar initials={currentUser.avatar} online /><span className="profile-name"><b>{currentUser.name}</b><small>{formatCount(currentUser.karma)} karma</small></span><ChevronDown size={15} /></button>
        </div>
      </div>
    </header>
  );
}

function Sidebar({
  page, navigate, subscribed, open, setOpen, communities,
}: { page: Page; navigate: (page: Page) => void; subscribed: Set<string>; open: boolean; setOpen: (value: boolean) => void; communities: CommunityProfile[] }) {
  const nav = (next: Page) => { navigate(next); setOpen(false); };
  const is = (type: Page['type']) => page.type === type;
  const joined = communities.filter(c => subscribed.has(c.id));
  const recent = communities.filter(c => c.dynamic && !subscribed.has(c.id)).sort((a, b) => (b.addedAt || 0) - (a.addedAt || 0)).slice(0, 5);
  return (
    <>
      {open && <button className="sidebar-backdrop" onClick={() => setOpen(false)} aria-label="Close navigation" />}
      <aside className={`sidebar ${open ? 'sidebar-open' : ''}`}>
        <nav className="sidebar-nav">
          <div className="nav-group primary-nav">
            <button className={is('home') ? 'active' : ''} onClick={() => nav({ type: 'home' })}><Home /><span>Home</span></button>
            <button className={is('explore') ? 'active' : ''} onClick={() => nav({ type: 'explore' })}><Compass /><span>Discover</span></button>
            <button className={is('saved') ? 'active' : ''} onClick={() => nav({ type: 'saved' })}><Bookmark /><span>Saved</span></button>
          </div>
          <div className="nav-separator" />
          <div className="nav-group">
            <div className="nav-label"><span>Your communities</span><button onClick={() => nav({ type: 'explore' })} aria-label="Find communities"><Plus size={15} /></button></div>
            {joined.slice(0, 10).map(community => (
              <button key={community.id} className={page.type === 'community' && page.id === community.id ? 'active' : ''} onClick={() => nav({ type: 'community', id: community.id })}>
                <CommunityAvatar community={community} size="sm" /><span>{community.name}</span>{community.dynamic && <i className="live-dot" />}
              </button>
            ))}
            <button className="muted-nav" onClick={() => nav({ type: 'explore' })}><LayoutGrid /><span>Browse all communities</span></button>
          </div>
          {recent.length > 0 && (
            <>
              <div className="nav-separator" />
              <div className="nav-group">
                <div className="nav-label"><span>Recently simulated</span></div>
                {recent.map(community => (
                  <button key={community.id} className={page.type === 'community' && page.id === community.id ? 'active' : ''} onClick={() => nav({ type: 'community', id: community.id })}>
                    <CommunityAvatar community={community} size="sm" /><span>{community.name}</span>
                  </button>
                ))}
              </div>
            </>
          )}
          <div className="nav-separator" />
          <div className="nav-group utility-nav">
            <button className={is('profile') ? 'active' : ''} onClick={() => nav({ type: 'profile' })}><User /><span>Profile</span></button>
            <button className={is('settings') ? 'active' : ''} onClick={() => nav({ type: 'settings' })}><Settings /><span>Settings</span></button>
            <button onClick={() => nav({ type: 'settings' })}><CircleHelp /><span>How this works</span></button>
          </div>
        </nav>
        <div className="sidebar-footer"><span>Fora © 2026 · simulated content</span><span><button onClick={() => nav({ type: 'settings' })}>Guidelines</button> · <button onClick={() => nav({ type: 'settings' })}>Privacy</button></span></div>
      </aside>
    </>
  );
}

function SortBar({ sort, setSort, compact = false }: { sort: SortOption; setSort: (sort: SortOption) => void; compact?: boolean }) {
  return (
    <div className={`sortbar ${compact ? 'sortbar-compact' : ''}`}>
      <div className="sort-options">
        {sortOptions.map(option => <button key={option.name} className={sort === option.name ? 'active' : ''} onClick={() => setSort(option.name)}>{option.icon}<span>{option.name}</span></button>)}
      </div>
      {!compact && <button className="sort-layout" aria-label="Feed layout"><ListFilter size={17} /><ChevronDown size={13} /></button>}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Posts                                                               */
/* ------------------------------------------------------------------ */

function PostCard({
  post, community, onOpen, onCommunity, vote, onVote, saved, onSave, notify,
}: {
  post: Post; community: CommunityProfile; onOpen: () => void; onCommunity: () => void; vote: VoteState;
  onVote: (vote: VoteState) => void; saved: boolean; onSave: () => void; notify: (message: string) => void;
}) {
  const adjustedScore = post.score + (vote === 'up' ? 1 : vote === 'down' ? -1 : 0);
  const click = (event: React.MouseEvent, action: () => void) => { event.stopPropagation(); action(); };
  return (
    <article className="post-card" onClick={onOpen} tabIndex={0} onKeyDown={event => event.key === 'Enter' && onOpen()}>
      <div className="vote-rail" onClick={event => event.stopPropagation()}>
        <button className={vote === 'up' ? 'voted-up' : ''} onClick={() => onVote(vote === 'up' ? null : 'up')} aria-label="Upvote"><ArrowUp size={19} /></button>
        <strong>{formatCount(adjustedScore)}</strong>
        <button className={vote === 'down' ? 'voted-down' : ''} onClick={() => onVote(vote === 'down' ? null : 'down')} aria-label="Downvote"><ArrowDown size={19} /></button>
      </div>
      <div className="post-main">
        <div className="post-meta">
          <button className="post-community" onClick={event => click(event, onCommunity)}><CommunityAvatar community={community} size="sm" /><b>{community.name}</b></button>
          <span>·</span><span>u/{post.author}</span><span>·</span><span>{post.time}</span>
          <AiPill generator={post.generator} />
          {post.trend === 'rising' && <span className="trend-label"><TrendingUp size={13} /> Rising</span>}
        </div>
        <h2 className="post-title">{post.title}</h2>
        <div className="post-tags">
          {post.flair && <span className="flair" style={{ background: `${post.flairColor || community.color}16`, color: post.flairColor || community.color }}>{post.flair}</span>}
          {post.archetype && <span className="archetype-tag">{post.archetype}</span>}
          {post.readTime && <span className="read-time">{post.readTime}</span>}
          {post.domain && <span className="link-domain"><Link2 size={11} />{post.domain}</span>}
        </div>
        {post.body && <RichBody text={post.body} compact />}
        {post.concept && <ConceptCard post={post} />}
        {post.image && <div className="post-image-wrap"><img className="post-image" src={post.image} alt={post.imageAlt || ''} loading="lazy" /><span className="image-badge"><ImageIcon size={14} /> Illustrative image</span></div>}
        {post.pollOptions && <div className="poll-compact">{post.pollOptions.slice(0, 3).map(option => <div key={option.label}><span>{option.label}</span><i style={{ width: `${Math.max(8, Math.min(96, option.votes / 25))}%` }} /></div>)}</div>}
        {post.topicLabel && <div className="topic-trace"><Sparkles size={12} /> inspired by current talk about <b>{post.topicLabel}</b></div>}
        <div className="post-actions" onClick={event => event.stopPropagation()}>
          <button onClick={onOpen}><MessageCircle size={17} /><span>{formatCount(post.comments)} comments</span></button>
          <div className="mobile-score"><ArrowUp size={16} /><b>{formatCount(adjustedScore)}</b></div>
          <button onClick={() => { navigator.clipboard?.writeText(`${window.location.origin}/#post/${post.id}`); notify('Link copied to clipboard'); }}><Share2 size={17} /><span>Share</span></button>
          <button className={saved ? 'saved-action' : ''} onClick={onSave}>{saved ? <BookmarkCheck size={17} /> : <Bookmark size={17} />}<span>{saved ? 'Saved' : 'Save'}</span></button>
          <button className="more-action" onClick={() => notify('Simulated post — generated locally from public signals')}><MoreHorizontal size={18} /></button>
        </div>
      </div>
    </article>
  );
}

function PostSkeleton() {
  return <div className="post-card skeleton-card"><div className="skeleton-vote" /><div className="skeleton-content"><div className="skeleton-line w40" /><div className="skeleton-line title-line" /><div className="skeleton-line w90" /><div className="skeleton-line w70" /><div className="skeleton-actions" /></div></div>;
}

interface FeedProps {
  posts: Post[];
  sort: SortOption;
  setSort: (sort: SortOption) => void;
  navigate: (page: Page) => void;
  votes: Record<string, VoteState>;
  setVote: (id: string, value: VoteState) => void;
  saved: Set<string>;
  toggleSaved: (id: string) => void;
  notify: (message: string) => void;
  communityFor: (id: string) => CommunityProfile;
  loading?: boolean;
  loadingMore?: boolean;
  sentinelRef?: React.RefObject<HTMLDivElement | null>;
  heading?: string;
  subheading?: string;
  emptyAction?: () => void;
}

function Feed(props: FeedProps) {
  const { posts, loading, loadingMore, sentinelRef, heading, subheading } = props;
  return (
    <div className="feed-column">
      {heading && <div className="section-heading"><h2>{heading}</h2><span>{subheading}</span></div>}
      <SortBar sort={props.sort} setSort={props.setSort} />
      {loading ? <><PostSkeleton /><PostSkeleton /><PostSkeleton /></> : posts.length ? posts.map(post => (
        <PostCard
          key={post.id}
          post={post}
          community={props.communityFor(post.communityId)}
          onOpen={() => props.navigate({ type: 'post', id: post.id })}
          onCommunity={() => props.navigate({ type: 'community', id: post.communityId })}
          vote={props.votes[post.id] || null}
          onVote={value => props.setVote(post.id, value)}
          saved={props.saved.has(post.id)}
          onSave={() => props.toggleSaved(post.id)}
          notify={props.notify}
        />
      )) : <EmptyState icon={<FileText />} title="Nothing here yet" text="Follow a community or search any subreddit to simulate it." action="Discover communities" onAction={props.emptyAction} />}
      {sentinelRef && (
        <div ref={sentinelRef} className="feed-sentinel">
          {loadingMore
            ? <><LoaderCircle className="spin" size={20} /><span>Generating more posts…</span></>
            : <span>Keep scrolling — the feed keeps writing itself</span>}
        </div>
      )}
    </div>
  );
}

function EmptyState({ icon, title, text, action, onAction }: { icon: ReactNode; title: string; text: string; action?: string; onAction?: () => void }) {
  return <div className="empty-state"><span className="empty-icon">{icon}</span><h2>{title}</h2><p>{text}</p>{action && onAction && <button className="primary-button" onClick={onAction}>{action}</button>}</div>;
}

/* ------------------------------------------------------------------ */
/* Context panels                                                      */
/* ------------------------------------------------------------------ */

function TopicRadar({ profile }: { profile: CultureProfile }) {
  if (!profile.topics.length) return null;
  return (
    <div className="topic-radar">
      {profile.topics.slice(0, 7).map(topic => (
        <div className="topic-row" key={topic.id}>
          <div className="topic-row-head">
            <b>{topic.label}</b>
            <span className={`momentum ${topic.momentum}`}>{topic.momentum === 'rising' ? '▲' : topic.momentum === 'fading' ? '▼' : '—'} {topic.momentum}</span>
          </div>
          <div className="topic-bar"><i style={{ width: `${Math.max(6, topic.heat * 100)}%` }} /></div>
          <small>{topic.kind} · {topic.mentions} signals{topic.entities.length ? ` · ${topic.entities.slice(0, 3).join(', ')}` : ''}</small>
        </div>
      ))}
    </div>
  );
}

function ContextPanel({ profile, refreshing, onRefresh, error }: {
  profile?: CultureProfile; refreshing: boolean; onRefresh: () => void; error?: string;
}) {
  if (!profile) {
    return <section className="surface-card context-card"><div className="card-title"><Sparkles size={18} /><h3>Reading the real community…</h3></div><p className="side-copy">Fetching public signals.</p></section>;
  }
  const mix = profile.formatMix;
  return (
    <section className="surface-card context-card">
      <div className="card-title">
        <Sparkles size={18} />
        <h3>What r/{profile.subreddit} is talking about</h3>
        <button className="icon-button tiny" onClick={onRefresh} disabled={refreshing} aria-label="Refresh context">
          <RefreshCw size={15} className={refreshing ? 'spin' : ''} />
        </button>
      </div>
      <div className="context-status">
        <ContextBadge profile={profile} refreshing={refreshing} />
        {profile.source === 'live' && <small>{profile.sampleSize} posts · last {profile.windowHours}h{profile.transport ? ` · via ${profile.transport}` : ''}</small>}
        {profile.source !== 'live' && <small>{error || 'Using durable subject matter instead of current trends.'}</small>}
      </div>
      <TopicRadar profile={profile} />
      {profile.rising.length > 0 && (
        <div className="context-block"><h4>Gaining attention</h4><div className="chip-row">{profile.rising.slice(0, 6).map(term => <span key={term} className="chip rising-chip"><TrendingUp size={11} /> {term}</span>)}</div></div>
      )}
      {profile.entities.length > 0 && (
        <div className="context-block"><h4>Names that keep coming up</h4><div className="chip-row">{profile.entities.slice(0, 8).map(entity => <span key={entity.term} className="chip">{entity.term}</span>)}</div></div>
      )}
      {profile.slang.length > 0 && (
        <div className="context-block"><h4>Community vocabulary</h4><div className="chip-row">{profile.slang.slice(0, 8).map(term => <span key={term} className="chip soft-chip">{term}</span>)}</div></div>
      )}
      <div className="context-block">
        <h4>How people post</h4>
        <div className="mix-bar">
          <i className="mix-text" style={{ width: `${mix.text * 100}%` }} title={`Text ${Math.round(mix.text * 100)}%`} />
          <i className="mix-image" style={{ width: `${(mix.image + mix.video) * 100}%` }} title={`Visual ${Math.round((mix.image + mix.video) * 100)}%`} />
          <i className="mix-link" style={{ width: `${mix.link * 100}%` }} title={`Links ${Math.round(mix.link * 100)}%`} />
        </div>
        <small className="mix-legend"><b>{Math.round(mix.text * 100)}%</b> text · <b>{Math.round((mix.image + mix.video) * 100)}%</b> visual · <b>{Math.round(mix.link * 100)}%</b> links</small>
        <small className="tone-line">Tone: humour {Math.round(profile.tone.humor * 100)}% · formality {Math.round(profile.tone.formality * 100)}% · questions {Math.round(profile.tone.questionRate * 100)}%</small>
      </div>
      {profile.notes.length > 0 && (
        <ul className="context-notes">{profile.notes.slice(0, 4).map(note => <li key={note}>{note}</li>)}</ul>
      )}
    </section>
  );
}

function SimulationBanner({ community }: { community: CommunityProfile }) {
  const source = community.sourceSubreddit;
  return (
    <div className="simulation-banner">
      <ShieldCheck size={17} />
      <p>
        <b>Simulated community.</b> Every post and comment here is generated by Fora using public signals about{' '}
        {source ? <>r/{source}</> : 'this topic'}. Nothing below is a real Reddit post, and no real Reddit user wrote it.
        {source && <> <a href={`https://www.reddit.com/r/${source}/`} target="_blank" rel="noreferrer noopener">Visit the real r/{source} <ExternalLink size={11} /></a></>}
      </p>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* Infinite scrolling                                                  */
/* ------------------------------------------------------------------ */

function useInfiniteScroll(onLoadMore: () => Promise<void>, enabled: boolean, key: string) {
  const ref = useRef<HTMLDivElement>(null);
  const handler = useRef(onLoadMore);
  handler.current = onLoadMore;

  useEffect(() => {
    const node = ref.current;
    if (!node || !enabled) return;
    let locked = false;
    const observer = new IntersectionObserver(async entries => {
      if (!entries[0].isIntersecting || locked) return;
      locked = true;
      try {
        await handler.current();
      } finally {
        locked = false;
        // Re-arm so a still-visible sentinel keeps the feed flowing.
        observer.unobserve(node);
        window.setTimeout(() => observer.observe(node), 240);
      }
    }, { rootMargin: '900px 0px' });
    observer.observe(node);
    return () => observer.disconnect();
  }, [enabled, key]);

  return ref;
}

/* ------------------------------------------------------------------ */
/* Pages                                                               */
/* ------------------------------------------------------------------ */

function HomeHero({ onSimulate, count }: { onSimulate: (name: string) => void; count: number }) {
  const [value, setValue] = useState('');
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (value.trim()) onSimulate(value.trim());
  };
  return (
    <div className="daily-mix">
      <div>
        <span className="eyebrow"><Sparkles size={14} /> Infinite simulation</span>
        <h1>Any subreddit.<br />Endlessly rewritten.</h1>
        <p>Type a subreddit and Fora reads what that community is actually talking about right now, then writes an original feed in its voice. {count} communities simulated so far.</p>
        <form className="hero-search" onSubmit={submit}>
          <span>r/</span>
          <input value={value} onChange={event => setValue(event.target.value)} placeholder="Deltarune" aria-label="Subreddit to simulate" />
          <button className="primary-button small" type="submit"><Wand2 size={15} /> Simulate</button>
        </form>
        <div className="hero-chips">
          {POPULAR_SUBS.slice(0, 5).map(name => (
            <button key={name} onClick={() => onSimulate(name)}>r/{name}</button>
          ))}
        </div>
      </div>
      <div className="mix-visual" aria-hidden="true"><span className="mix-ring ring-one" /><span className="mix-ring ring-two" /><span className="mix-card card-a">r/</span><span className="mix-card card-b">✦</span><span className="mix-card card-c">↗</span></div>
    </div>
  );
}

function RightRail({ navigate, subscribed, toggleSubscribe, communities, trending, onSimulate }: {
  navigate: (page: Page) => void; subscribed: Set<string>; toggleSubscribe: (id: string) => void;
  communities: CommunityProfile[]; trending: { label: string; community: CommunityProfile; momentum: string }[];
  onSimulate: (name: string) => void;
}) {
  const suggestions = communities.filter(c => !subscribed.has(c.id)).slice(0, 4);
  return (
    <aside className="right-rail">
      <section className="rail-card">
        <div className="rail-heading"><h3>Simulate a subreddit</h3><Wand2 size={16} /></div>
        <p className="rail-copy">Not in your list yet? Any of these spin up a fresh community.</p>
        <div className="quick-subs">
          {POPULAR_SUBS.slice(0, 8).map(name => <button key={name} onClick={() => onSimulate(name)}>r/{name}</button>)}
        </div>
      </section>
      {trending.length > 0 && (
        <section className="rail-card">
          <div className="rail-heading"><h3>Detected in real communities</h3><TrendingUp size={17} /></div>
          <div className="trending-list">
            {trending.slice(0, 5).map((topic, index) => (
              <button key={`${topic.community.id}-${topic.label}`} onClick={() => navigate({ type: 'community', id: topic.community.id })}>
                <span className="trend-number">{String(index + 1).padStart(2, '0')}</span>
                <span><b>{topic.label}</b><small>{topic.community.name} · {topic.momentum}</small></span>
                <ChevronDown className="trend-arrow" size={16} />
              </button>
            ))}
          </div>
        </section>
      )}
      <section className="rail-card">
        <div className="rail-heading"><h3>Communities to explore</h3><button onClick={() => navigate({ type: 'explore' })}>See all</button></div>
        <div className="community-list">
          {suggestions.map(community => <div className="community-row" key={community.id}>
            <button className="community-row-main" onClick={() => navigate({ type: 'community', id: community.id })}><CommunityAvatar community={community} /><span><b>{community.name}</b><small>{community.members ? `${formatCount(community.members)} members` : 'simulated'}</small></span></button>
            <button className="join-small" onClick={() => toggleSubscribe(community.id)}>Join</button>
          </div>)}
        </div>
      </section>
      <div className="rail-note"><ShieldCheck size={16} /><span>All content is AI-generated and safety filtered. Real subreddits supply context only — never text.</span></div>
      <div className="rail-links"><button onClick={() => navigate({ type: 'settings' })}>About</button><button onClick={() => navigate({ type: 'settings' })}>Guidelines</button><span>Fora © 2026</span></div>
    </aside>
  );
}

function HomePage(props: {
  posts: Post[]; sort: SortOption; setSort: (sort: SortOption) => void; navigate: (page: Page) => void;
  votes: Record<string, VoteState>; setVote: (id: string, value: VoteState) => void; saved: Set<string>;
  toggleSaved: (id: string) => void; notify: (message: string) => void; subscribed: Set<string>;
  toggleSubscribe: (id: string) => void; loading: boolean; loadingMore: boolean;
  sentinelRef: React.RefObject<HTMLDivElement | null>; communities: CommunityProfile[];
  communityFor: (id: string) => CommunityProfile; onSimulate: (name: string) => void;
  trending: { label: string; community: CommunityProfile; momentum: string }[];
}) {
  return (
    <div className="page-grid home-grid">
      <main>
        <HomeHero onSimulate={props.onSimulate} count={props.communities.length} />
        <Feed
          posts={props.posts}
          sort={props.sort}
          setSort={props.setSort}
          navigate={props.navigate}
          votes={props.votes}
          setVote={props.setVote}
          saved={props.saved}
          toggleSaved={props.toggleSaved}
          notify={props.notify}
          communityFor={props.communityFor}
          loading={props.loading}
          loadingMore={props.loadingMore}
          sentinelRef={props.sentinelRef}
          emptyAction={() => props.navigate({ type: 'explore' })}
        />
      </main>
      <RightRail
        navigate={props.navigate}
        subscribed={props.subscribed}
        toggleSubscribe={props.toggleSubscribe}
        communities={props.communities}
        trending={props.trending}
        onSimulate={props.onSimulate}
      />
    </div>
  );
}

function CreatingView({ name, stage, detail, error, onRetry, onHome }: {
  name: string; stage: CreateStage; detail: string; error?: string; onRetry: () => void; onHome: () => void;
}) {
  const stages: { id: CreateStage; label: string }[] = [
    { id: 'lookup', label: `Finding r/${name}` },
    { id: 'reading', label: 'Reading recent and popular posts' },
    { id: 'analysing', label: 'Extracting topics, tone and formats' },
    { id: 'writing', label: 'Writing original posts in that voice' },
  ];
  const activeIndex = stages.findIndex(item => item.id === stage);
  if (error) {
    return (
      <div className="creating-view">
        <div className="creating-card error">
          <span className="creating-icon"><TriangleAlert size={26} /></span>
          <h1>Could not simulate r/{name}</h1>
          <p>{error}</p>
          <div className="creating-actions">
            <button className="primary-button" onClick={onRetry}><RefreshCw size={15} /> Try again</button>
            <button className="secondary-button" onClick={onHome}>Back home</button>
          </div>
        </div>
      </div>
    );
  }
  return (
    <div className="creating-view">
      <div className="creating-card">
        <span className="creating-icon"><Wand2 size={26} /></span>
        <h1>Building r/{name}</h1>
        <p>{detail}</p>
        <ol className="creating-steps">
          {stages.map((item, index) => (
            <li key={item.id} className={index < activeIndex ? 'done' : index === activeIndex ? 'active' : ''}>
              <span>{index < activeIndex ? <Check size={13} /> : index === activeIndex ? <LoaderCircle size={13} className="spin" /> : index + 1}</span>
              {item.label}
            </li>
          ))}
        </ol>
        <small>Real posts are never copied — only aggregate signal is used.</small>
      </div>
    </div>
  );
}

function CommunityPage({
  community, posts, sort, setSort, navigate, votes, setVote, saved, toggleSaved, notify, subscribed,
  toggleSubscribe, loading, loadingMore, sentinelRef, profile, refreshing, onRefresh, contextError, communityFor,
}: {
  community: CommunityProfile; posts: Post[]; sort: SortOption; setSort: (sort: SortOption) => void;
  navigate: (page: Page) => void; votes: Record<string, VoteState>; setVote: (id: string, value: VoteState) => void;
  saved: Set<string>; toggleSaved: (id: string) => void; notify: (message: string) => void; subscribed: Set<string>;
  toggleSubscribe: (id: string) => void; loading: boolean; loadingMore: boolean;
  sentinelRef: React.RefObject<HTMLDivElement | null>; profile?: CultureProfile; refreshing: boolean;
  onRefresh: () => void; contextError?: string; communityFor: (id: string) => CommunityProfile;
}) {
  const [tab, setTab] = useState<'posts' | 'about' | 'context'>('posts');
  return (
    <div className="community-page">
      <section className="community-hero" style={{ '--community': community.color, '--community-soft': community.colorSoft } as React.CSSProperties}>
        <div className="community-banner"><span className="banner-symbol symbol-one">{community.icon}</span><span className="banner-symbol symbol-two">{community.icon}</span><span className="banner-grid" /></div>
        <div className="community-identity">
          <CommunityAvatar community={community} size="xl" />
          <div className="community-name">
            <div className="community-title-row"><h1>{community.displayName}</h1><span className="sim-tag"><Wand2 size={11} /> simulated</span></div>
            <p>{community.name} <ContextBadge profile={profile} refreshing={refreshing} /></p>
          </div>
          <div className="community-stats">
            <span><b>{community.members ? formatCount(community.members) : '—'}</b><small>members on Reddit</small></span>
            <i />
            <span><b>{community.online ? formatCount(community.online) : '—'}</b><small>online</small></span>
          </div>
          <button className={subscribed.has(community.id) ? 'joined-button' : 'join-button'} onClick={() => toggleSubscribe(community.id)}>{subscribed.has(community.id) ? <><Check size={17} /> Joined</> : <><Plus size={17} /> Join community</>}</button>
          <button className="icon-button community-more" onClick={onRefresh} aria-label="Resync context"><RefreshCw size={19} className={refreshing ? 'spin' : ''} /></button>
        </div>
        <div className="community-tabs">
          <button className={tab === 'posts' ? 'active' : ''} onClick={() => setTab('posts')}>Posts</button>
          <button className={tab === 'context' ? 'active' : ''} onClick={() => setTab('context')}>Live context</button>
          <button className={tab === 'about' ? 'active' : ''} onClick={() => setTab('about')}>About</button>
        </div>
      </section>
      <div className="community-layout">
        <main>
          <SimulationBanner community={community} />
          {tab === 'posts' && (
            <Feed
              posts={posts}
              sort={sort}
              setSort={setSort}
              navigate={navigate}
              votes={votes}
              setVote={setVote}
              saved={saved}
              toggleSaved={toggleSaved}
              notify={notify}
              communityFor={communityFor}
              loading={loading}
              loadingMore={loadingMore}
              sentinelRef={sentinelRef}
              emptyAction={() => navigate({ type: 'home' })}
            />
          )}
          {tab === 'context' && <div className="context-tab">{profile ? <ContextPanel profile={profile} refreshing={refreshing} onRefresh={onRefresh} error={contextError} /> : <PostSkeleton />}</div>}
          {tab === 'about' && (
            <section className="community-about-mobile surface-card">
              <h2>About this simulation</h2>
              <p>{community.description}</p>
              <div className="profile-details">
                <div><h4>Context source</h4><p>{community.sourceSubreddit ? `Public signals from r/${community.sourceSubreddit}` : 'Built-in profile'}</p></div>
                <div><h4>Detected tone</h4><p>{community.tone}</p></div>
                <div><h4>Common formats</h4><p>{community.preferredFormats.join(' · ') || 'Mixed'}</p></div>
                <div><h4>Vocabulary</h4><p>{community.vocabulary.join(' · ') || '—'}</p></div>
              </div>
              <ol className="rules-list">{community.rules.map((rule, index) => <li key={rule}><span>{index + 1}</span><p>{rule}</p></li>)}</ol>
            </section>
          )}
        </main>
        <aside className="community-sidebar">
          <ContextPanel profile={profile} refreshing={refreshing} onRefresh={onRefresh} error={contextError} />
          <section className="surface-card about-card">
            <div className="card-title"><Info size={18} /><h3>About</h3></div>
            <p>{community.description}</p>
            <div className="about-meta">
              <span><Users size={16} /> {community.category}</span>
              <span><ShieldCheck size={16} /> Safety filtered before display</span>
            </div>
          </section>
          <section className="surface-card rules-card">
            <div className="card-title"><ShieldCheck size={18} /><h3>Community rules</h3></div>
            <ol>{community.rules.slice(0, 5).map((rule, index) => <li key={rule}><span>{index + 1}</span><p>{rule}</p></li>)}</ol>
          </section>
        </aside>
      </div>
    </div>
  );
}

function CommentItem({ comment, depth = 0, onReply }: { comment: Comment; depth?: number; onReply: (parentId: string, text: string) => void }) {
  const [collapsed, setCollapsed] = useState(false);
  const [replying, setReplying] = useState(false);
  const [reply, setReply] = useState('');
  const submit = () => { if (!reply.trim()) return; onReply(comment.id, reply.trim()); setReply(''); setReplying(false); };
  return (
    <div className={`comment depth-${Math.min(depth, 3)} ${collapsed ? 'comment-collapsed' : ''}`}>
      <div className="comment-line" onClick={() => setCollapsed(!collapsed)} />
      <div className="comment-head"><UserAvatar initials={comment.avatar} size="sm" /><b>{comment.author}</b>{comment.isOp && <span className="op-badge">OP</span>}{comment.isMod && <span className="mod-badge">MOD</span>}<span>· {comment.time}</span><button className="collapse-comment" onClick={() => setCollapsed(!collapsed)}>{collapsed ? `[+${(comment.replies?.length || 0) + 1}]` : '–'}</button></div>
      {!collapsed && <>
        <p className="comment-body">{comment.body}</p>
        <div className="comment-actions"><button><ArrowUp size={15} /></button><b>{formatCount(comment.score)}</b><button><ArrowDown size={15} /></button><button onClick={() => setReplying(!replying)}><MessageCircle size={14} /> Reply</button><button><Trophy size={14} /> Award</button><button><MoreHorizontal size={15} /></button></div>
        {replying && <div className="inline-reply"><UserAvatar initials={currentUser.avatar} size="sm" /><div><textarea autoFocus value={reply} onChange={event => setReply(event.target.value)} placeholder={`Reply to ${comment.author}`} /><div><button className="secondary-button" onClick={() => setReplying(false)}>Cancel</button><button className="primary-button small" onClick={submit}><Send size={14} /> Reply</button></div></div></div>}
        {comment.replies?.map(child => <CommentItem key={child.id} comment={child} depth={depth + 1} onReply={onReply} />)}
      </>}
    </div>
  );
}

function PostDetail({ post, community, navigate, vote, onVote, saved, onSave, notify, onComment, onReply, subscribed, toggleSubscribe }: {
  post: Post; community: CommunityProfile; navigate: (page: Page) => void; vote: VoteState; onVote: (value: VoteState) => void;
  saved: boolean; onSave: () => void; notify: (message: string) => void; onComment: (text: string) => void;
  onReply: (parentId: string, text: string) => void; subscribed: Set<string>; toggleSubscribe: (id: string) => void;
}) {
  const [comment, setComment] = useState('');
  const [commentSort, setCommentSort] = useState('Best');
  const submitComment = () => { if (!comment.trim()) return; onComment(comment.trim()); setComment(''); notify('Your comment is now live'); };
  return (
    <div className="post-page">
      <button className="back-button" onClick={() => navigate({ type: 'community', id: post.communityId })}><ArrowLeft size={17} /> Back to {community.name}</button>
      <div className="post-layout">
        <main>
          <article className="post-detail-card">
            <div className="detail-community-row">
              <button onClick={() => navigate({ type: 'community', id: community.id })}><CommunityAvatar community={community} /><span><b>{community.name}</b><small>u/{post.author} · {post.time} · <AiPill generator={post.generator} /></small></span></button>
              <button className={subscribed.has(community.id) ? 'joined-button small-button' : 'join-small'} onClick={() => toggleSubscribe(community.id)}>{subscribed.has(community.id) ? 'Joined' : 'Join'}</button>
            </div>
            <div className="detail-vote"><button className={vote === 'up' ? 'voted-up' : ''} onClick={() => onVote(vote === 'up' ? null : 'up')}><ArrowUp /></button><b>{formatCount(post.score + (vote === 'up' ? 1 : vote === 'down' ? -1 : 0))}</b><button className={vote === 'down' ? 'voted-down' : ''} onClick={() => onVote(vote === 'down' ? null : 'down')}><ArrowDown /></button></div>
            <div className="detail-content">
              <div className="post-tags">
                {post.flair && <span className="flair" style={{ background: `${post.flairColor || community.color}16`, color: post.flairColor || community.color }}>{post.flair}</span>}
                {post.archetype && <span className="archetype-tag">{post.archetype}</span>}
                {post.readTime && <span className="read-time">{post.readTime}</span>}
              </div>
              <h1>{post.title}</h1>
              {post.body && <RichBody text={post.body} />}
              {post.concept && <ConceptCard post={post} />}
              {post.image && <div className="detail-image"><img src={post.image} alt={post.imageAlt || ''} /></div>}
              {post.pollOptions && (
                <div className="poll-full">
                  {post.pollOptions.map(option => {
                    const total = post.pollOptions!.reduce((sum, item) => sum + item.votes, 0) || 1;
                    return (
                      <div key={option.label} className="poll-option">
                        <div className="poll-option-head"><span>{option.label}</span><b>{Math.round((option.votes / total) * 100)}%</b></div>
                        <i style={{ width: `${(option.votes / total) * 100}%` }} />
                      </div>
                    );
                  })}
                  <small>{formatCount(post.pollOptions.reduce((sum, item) => sum + item.votes, 0))} simulated votes</small>
                </div>
              )}
              {post.topicLabel && <div className="topic-trace detail-trace"><Sparkles size={12} /> Written from current signal about <b>{post.topicLabel}</b></div>}
              <div className="detail-actions"><button><MessageCircle size={17} /> {formatCount(post.comments)} comments</button><button onClick={() => { navigator.clipboard?.writeText(window.location.href); notify('Link copied to clipboard'); }}><Share2 size={17} /> Share</button><button className={saved ? 'saved-action' : ''} onClick={onSave}>{saved ? <BookmarkCheck size={17} /> : <Bookmark size={17} />} {saved ? 'Saved' : 'Save'}</button></div>
            </div>
          </article>
          <section className="comments-card">
            <div className="comment-composer"><UserAvatar initials={currentUser.avatar} /><div><textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="Add to the conversation" /><div className="composer-bottom"><span><ShieldCheck size={14} /> Your replies stay on this device</span><button className="primary-button small" disabled={!comment.trim()} onClick={submitComment}><Send size={14} /> Comment</button></div></div></div>
            <div className="comments-head"><h2>Comments <span>{formatCount(post.comments)}</span></h2><div className="comment-sort">Sort by <button onClick={() => setCommentSort(commentSort === 'Best' ? 'New' : 'Best')}>{commentSort} <ChevronDown size={13} /></button></div></div>
            <div className="comment-tree">{post.commentTree?.length ? post.commentTree.map(item => <CommentItem key={item.id} comment={item} onReply={onReply} />) : <EmptyState icon={<MessageCircle />} title="Start the conversation" text="Be the first to reply." />}</div>
          </section>
        </main>
        <aside className="post-side">
          <section className="surface-card post-community-card" style={{ '--community': community.color } as React.CSSProperties}>
            <div className="side-cover" /><CommunityAvatar community={community} size="lg" />
            <h3>{community.displayName}</h3><p>{community.description}</p>
            <div><span><b>{community.members ? formatCount(community.members) : '—'}</b><small>members</small></span><span><b>{community.online ? formatCount(community.online) : '—'}</b><small>online</small></span></div>
            <button className="secondary-button full" onClick={() => navigate({ type: 'community', id: community.id })}>Visit community</button>
          </section>
          <section className="surface-card"><div className="card-title"><Wand2 size={18} /><h3>How this was made</h3></div><p className="side-copy">Fora sampled public activity from {community.sourceSubreddit ? `r/${community.sourceSubreddit}` : 'this topic'}, reduced it to topics, tone and formats, then wrote this thread from scratch. The post, the username and every comment are synthetic.</p></section>
        </aside>
      </div>
    </div>
  );
}

function ExplorePage({ navigate, subscribed, toggleSubscribe, communities, onSimulate }: {
  navigate: (page: Page) => void; subscribed: Set<string>; toggleSubscribe: (id: string) => void;
  communities: CommunityProfile[]; onSimulate: (name: string) => void;
}) {
  const [category, setCategory] = useState('All');
  const [value, setValue] = useState('');
  const categories = ['All', ...Array.from(new Set(communities.map(c => c.category)))];
  const filtered = category === 'All' ? communities : communities.filter(c => c.category === category);
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (value.trim()) onSimulate(value.trim());
  };
  return (
    <div className="wide-page explore-page">
      <section className="explore-hero">
        <div>
          <span className="eyebrow"><Compass size={14} /> Discover</span>
          <h1>Every subreddit,<br />simulated on demand.</h1>
          <p>Search a name and Fora reads the real community for context, then generates an endless original feed in its style.</p>
          <form className="hero-search" onSubmit={submit}>
            <span>r/</span>
            <input value={value} onChange={event => setValue(event.target.value)} placeholder="type any subreddit" aria-label="Subreddit to simulate" />
            <button className="primary-button small" type="submit"><Wand2 size={15} /> Simulate</button>
          </form>
        </div>
        <div className="explore-cloud">{communities.slice(0, 9).map((c, i) => <button key={c.id} style={{ '--x': `${(i * 31) % 80}%`, '--y': `${(i * 43) % 76}%`, '--delay': `${i * -.4}s`, background: c.colorSoft, color: c.color } as React.CSSProperties} onClick={() => navigate({ type: 'community', id: c.id })}>{c.icon}</button>)}</div>
      </section>
      <section className="featured-section">
        <div className="section-title"><div><span>Popular right now</span><h2>Spin up a new simulation</h2></div></div>
        <div className="quick-grid">
          {POPULAR_SUBS.map(name => (
            <button key={name} className="quick-card" onClick={() => onSimulate(name)}>
              <span className="quick-mark">r/</span>
              <b>{name}</b>
              <small>{communities.some(c => c.id === name.toLowerCase()) ? 'Already simulated' : 'Generate this community'}</small>
            </button>
          ))}
        </div>
      </section>
      <section className="all-communities">
        <div className="section-title"><div><span>Your library</span><h2>{communities.length} simulated communities</h2></div></div>
        <div className="category-scroll">{categories.map(item => <button key={item} className={item === category ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div>
        <div className="community-directory">
          {filtered.map(community => (
            <article key={community.id}>
              <button className="directory-main" onClick={() => navigate({ type: 'community', id: community.id })}>
                <CommunityAvatar community={community} size="lg" />
                <span>
                  <h3>{community.displayName}</h3><b>{community.name}</b><p>{community.description}</p>
                  <small><Users size={14} /> {community.members ? `${formatCount(community.members)} members` : 'simulated community'} <i /> {community.category}</small>
                </span>
              </button>
              <button className={subscribed.has(community.id) ? 'joined-button' : 'join-small'} onClick={() => toggleSubscribe(community.id)}>{subscribed.has(community.id) ? <><Check size={15} /> Joined</> : 'Join'}</button>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}

function SavedPage(props: FeedProps & { navigate: (page: Page) => void }) {
  return (
    <div className="center-page">
      <div className="simple-page-head"><div><span className="eyebrow"><Bookmark size={14} /> Your library</span><h1>Saved posts</h1><p>Simulated threads you wanted to keep.</p></div><span className="count-pill">{props.posts.length} saved</span></div>
      {props.posts.length
        ? <Feed {...props} loading={false} />
        : <EmptyState icon={<Bookmark />} title="Nothing saved yet" text="Save anything the simulation writes and it will appear here." action="Browse your feed" onAction={() => props.navigate({ type: 'home' })} />}
    </div>
  );
}

function SearchPage({ query, posts, navigate, communities, onSimulate, communityFor, votes, setVote, saved, toggleSaved, notify, sort, setSort }: {
  query: string; posts: Post[]; navigate: (page: Page) => void; communities: CommunityProfile[];
  onSimulate: (name: string) => void; communityFor: (id: string) => CommunityProfile;
  votes: Record<string, VoteState>; setVote: (id: string, value: VoteState) => void; saved: Set<string>;
  toggleSaved: (id: string) => void; notify: (message: string) => void; sort: SortOption; setSort: (sort: SortOption) => void;
}) {
  const [remote, setRemote] = useState<SubredditSuggestion[]>([]);
  const q = query.toLowerCase();
  const slug = normalizeSubredditName(query);

  useEffect(() => {
    let active = true;
    searchSubreddits(query, 6).then(results => { if (active) setRemote(results); });
    return () => { active = false; };
  }, [query]);

  const communityMatches = communities.filter(c => `${c.name} ${c.displayName} ${c.description}`.toLowerCase().includes(q));
  const postMatches = posts.filter(p => `${p.title} ${p.body || ''}`.toLowerCase().includes(q));
  const alreadyHave = communities.some(c => c.id === slug.toLowerCase());

  return (
    <div className="search-page center-page">
      <div className="simple-page-head"><div><span className="eyebrow"><Search size={14} /> Search</span><h1>Results for “{query}”</h1><p>{postMatches.length} generated posts · {communityMatches.length} simulated communities</p></div></div>

      {slug && !alreadyHave && (
        <button className="simulate-cta" onClick={() => onSimulate(slug)}>
          <span className="simulate-icon"><Wand2 size={20} /></span>
          <span><b>Simulate r/{slug}</b><small>Reads the real subreddit for context, then generates an endless original feed</small></span>
          <ArrowUp size={18} className="cta-arrow" />
        </button>
      )}

      {remote.filter(item => !communities.some(c => c.id === item.name.toLowerCase())).length > 0 && (
        <section className="search-communities">
          <h2>Real subreddits matching this</h2>
          {remote.filter(item => !communities.some(c => c.id === item.name.toLowerCase())).slice(0, 5).map(item => (
            <div key={item.name}>
              <button onClick={() => onSimulate(item.name)}>
                <span className="suggest-icon plain">r/</span>
                <span><b>{item.displayName}</b><small>{formatCount(item.subscribers)} members · {item.description.slice(0, 70) || 'no description'}</small></span>
              </button>
              <button className="join-small" onClick={() => onSimulate(item.name)}>Simulate</button>
            </div>
          ))}
        </section>
      )}

      {communityMatches.length > 0 && (
        <section className="search-communities">
          <h2>In your simulation</h2>
          {communityMatches.slice(0, 5).map(c => (
            <div key={c.id}>
              <button onClick={() => navigate({ type: 'community', id: c.id })}><CommunityAvatar community={c} /><span><b>{c.displayName}</b><small>{c.name} · {c.category}</small></span></button>
              <button className="join-small" onClick={() => navigate({ type: 'community', id: c.id })}>Open</button>
            </div>
          ))}
        </section>
      )}

      <section>
        <h2 className="search-section-label">Generated posts</h2>
        {postMatches.length
          ? <Feed posts={postMatches} sort={sort} setSort={setSort} navigate={navigate} votes={votes} setVote={setVote} saved={saved} toggleSaved={toggleSaved} notify={notify} communityFor={communityFor} />
          : <EmptyState icon={<Search />} title="No generated posts match" text="Simulate the subreddit above and the feed will fill in." />}
      </section>
    </div>
  );
}

function ProfilePage({ navigate, posts, communityFor }: { navigate: (page: Page) => void; posts: Post[]; communityFor: (id: string) => CommunityProfile }) {
  const userPosts = posts.slice(0, 3);
  return (
    <div className="profile-page center-page">
      <section className="profile-hero">
        <div className="profile-cover"><span /></div>
        <div className="profile-info"><UserAvatar initials={currentUser.avatar} size="lg" /><div><h1>{currentUser.displayName}</h1><span>u/{currentUser.name}</span><p>{currentUser.bio}</p></div><button className="secondary-button"><PenLine size={16} /> Edit profile</button></div>
        <div className="profile-metrics"><span><b>{formatCount(currentUser.karma)}</b><small>Karma</small></span><span><b>{currentUser.posts}</b><small>Posts</small></span><span><b>{currentUser.comments}</b><small>Comments</small></span><span><b>{currentUser.joined}</b><small>Joined</small></span></div>
      </section>
      <div className="profile-tabs"><button className="active">Overview</button><button>Posts</button><button>Comments</button></div>
      <section className="profile-achievement"><span><Trophy size={22} /></span><div><b>Simulation explorer</b><p>You are browsing communities that write themselves.</p></div><small>Local profile</small></section>
      <div className="section-heading"><h2>Recent activity</h2></div>
      {userPosts.map((post, index) => (
        <button className="activity-row" key={post.id} onClick={() => navigate({ type: 'post', id: post.id })}>
          <span className={index === 1 ? 'comment-activity' : ''}>{index === 1 ? <MessageCircle size={18} /> : <ArrowUp size={18} />}</span>
          <div><small>{index === 1 ? `Commented in ${communityFor(post.communityId).name}` : `Upvoted in ${communityFor(post.communityId).name}`} · {post.time}</small><b>{post.title}</b><p>{(index === 1 ? post.commentTree?.[0]?.body : post.body)?.slice(0, 150)}…</p></div>
          <ChevronDown size={17} />
        </button>
      ))}
    </div>
  );
}

function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) {
  return <button className={`toggle ${checked ? 'on' : ''}`} onClick={onChange} role="switch" aria-checked={checked}><span /></button>;
}

function SettingsRow({ title, text, control }: { title: string; text: string; control: ReactNode }) {
  return <div className="settings-row"><div><b>{title}</b><span>{text}</span></div>{control}</div>;
}

function SettingsPage({ theme, setTheme, notify, onClearCache }: {
  theme: string; setTheme: (value: 'light' | 'dark') => void; notify: (message: string) => void; onClearCache: () => void;
}) {
  const [model, setModel] = useState<ModelSettings>(() => loadModelSettings());
  const [proxy, setProxy] = useState(() => getCustomProxy());
  const [prefs, setPrefs] = useState({ autoRefresh: true, compact: false });
  const flip = (key: keyof typeof prefs) => setPrefs(value => ({ ...value, [key]: !value[key] }));

  const update = (patch: Partial<ModelSettings>) => {
    const next = { ...model, ...patch };
    if (patch.provider && !next.model) next.model = DEFAULT_MODELS[patch.provider] || '';
    setModel(next);
  };

  return (
    <div className="settings-page center-page">
      <div className="simple-page-head"><div><span className="eyebrow"><Settings size={14} /> Preferences</span><h1>Settings</h1><p>How the simulation reads Reddit and writes posts.</p></div></div>

      <section className="settings-section">
        <h2>How Fora works</h2>
        <p className="settings-copy">
          When you search a subreddit, Fora reads its public listings, reduces them to statistical signal — topic clusters,
          recurring names, tone measurements, format ratios — and generates brand-new posts from that signal. Real post text
          is never copied, stored, or displayed, and nothing here is presented as a genuine Reddit post or user.
        </p>
      </section>

      <section className="settings-section">
        <h2>Generation engine</h2>
        <p className="settings-copy">The built-in engine runs entirely on this device and needs no key. Add your own model key for richer writing — it is stored only in this browser and called directly from it.</p>
        <label className="field-label">Provider</label>
        <div className="provider-row">
          {(['none', 'openai', 'gemini', 'anthropic', 'custom'] as ModelProvider[]).map(provider => (
            <button key={provider} className={model.provider === provider ? 'active' : ''} onClick={() => update({ provider })}>
              {provider === 'none' ? 'Built-in engine' : provider === 'custom' ? 'OpenAI-compatible' : provider}
            </button>
          ))}
        </div>
        {model.provider !== 'none' && (
          <>
            <label className="field-label">API key</label>
            <input className="text-input" type="password" value={model.apiKey} onChange={event => update({ apiKey: event.target.value })} placeholder="sk-…" />
            <label className="field-label">Model</label>
            <input className="text-input" value={model.model} onChange={event => update({ model: event.target.value })} placeholder={DEFAULT_MODELS[model.provider] || 'model name'} />
            {model.provider === 'custom' && (
              <>
                <label className="field-label">Base URL</label>
                <input className="text-input" value={model.baseUrl} onChange={event => update({ baseUrl: event.target.value })} placeholder="https://your-gateway/v1" />
              </>
            )}
            <div className="settings-warning"><TriangleAlert size={15} /> Browser-side keys are visible to anyone with access to this device. Use a restricted key.</div>
          </>
        )}
        <button className="primary-button" onClick={() => { saveModelSettings(model); notify(modelIsConfigured(model) ? 'Model connected' : 'Using the built-in engine'); }}>Save engine settings</button>
      </section>

      <section className="settings-section">
        <h2>Reddit context</h2>
        <p className="settings-copy">Reddit does not allow direct browser requests, so Fora tries a chain of public read-only mirrors. If they are blocked on your network, point Fora at your own proxy.</p>
        <label className="field-label">Custom proxy template <span>optional</span></label>
        <input className="text-input" value={proxy} onChange={event => setProxy(event.target.value)} placeholder="https://my-worker.dev/?url={url}" />
        <div className="settings-actions">
          <button className="secondary-button" onClick={() => { setCustomProxy(proxy); notify(proxy ? 'Proxy saved' : 'Proxy cleared'); }}>Save proxy</button>
          <button className="secondary-button" onClick={onClearCache}>Clear cached context</button>
        </div>
        <SettingsRow title="Auto-refresh context" text="Re-read the real subreddit when a cached profile goes stale" control={<Toggle checked={prefs.autoRefresh} onChange={() => flip('autoRefresh')} />} />
      </section>

      <section className="settings-section">
        <h2>Appearance</h2>
        <div className="theme-cards">
          <button className={theme === 'light' ? 'active' : ''} onClick={() => setTheme('light')}><span className="theme-preview light-preview"><i /><i /><i /></span><b><Sun size={16} /> Light</b>{theme === 'light' && <Check size={17} />}</button>
          <button className={theme === 'dark' ? 'active' : ''} onClick={() => setTheme('dark')}><span className="theme-preview dark-preview"><i /><i /><i /></span><b><Moon size={16} /> Dark</b>{theme === 'dark' && <Check size={17} />}</button>
        </div>
        <SettingsRow title="Compact post cards" text="Fit more conversations on screen" control={<Toggle checked={prefs.compact} onChange={() => flip('compact')} />} />
      </section>
    </div>
  );
}

function CreatePostModal({ open, onClose, onPublish, subscribed, communities }: {
  open: boolean; onClose: () => void; onPublish: (post: Post) => void; subscribed: Set<string>; communities: CommunityProfile[];
}) {
  const available = communities.filter(c => subscribed.has(c.id));
  const pool = available.length ? available : communities;
  const [communityId, setCommunityId] = useState(pool[0]?.id || '');
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  useEffect(() => {
    if (open && !pool.some(c => c.id === communityId)) setCommunityId(pool[0]?.id || '');
  }, [open, pool, communityId]);
  if (!open) return null;
  const community = pool.find(c => c.id === communityId) || pool[0];
  if (!community) return null;
  const canPublish = Boolean(title.trim());
  const publish = () => {
    if (!canPublish) return;
    onPublish({
      id: `user-${Date.now()}`,
      communityId: community.id,
      author: currentUser.name,
      avatar: currentUser.avatar,
      title: title.trim(),
      body: body.trim() || undefined,
      flair: 'Discussion',
      flairColor: community.color,
      score: 1,
      comments: 0,
      time: 'now',
      ageMinutes: 0,
      type: 'text',
      commentTree: [],
      generated: false,
      generator: 'you',
    });
    setTitle('');
    setBody('');
    onClose();
  };
  return (
    <div className="modal-backdrop" onMouseDown={onClose}>
      <div className="create-modal" onMouseDown={event => event.stopPropagation()}>
        <div className="modal-head"><div><span className="eyebrow"><PenLine size={14} /> Add your own</span><h2>Create a post</h2></div><button className="icon-button" onClick={onClose}><X size={20} /></button></div>
        <label className="field-label">Community</label>
        <div className="select-wrap"><CommunityAvatar community={community} size="sm" /><select value={communityId} onChange={event => setCommunityId(event.target.value)}>{pool.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><ChevronDown size={16} /></div>
        <label className="field-label">Title <span>{title.length}/180</span></label>
        <input className="text-input" maxLength={180} value={title} onChange={event => setTitle(event.target.value)} placeholder={`Post to ${community.name}`} />
        <label className="field-label">Body <span>Optional</span></label>
        <textarea className="body-input" value={body} onChange={event => setBody(event.target.value)} placeholder="Say something…" />
        <div className="community-guidance"><ShieldCheck size={18} style={{ color: community.color }} /><span><b>Stays on this device</b><small>Your post joins the simulated feed locally. It is never sent to Reddit.</small></span></div>
        <div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!canPublish} onClick={publish}>Publish post <ArrowUp size={16} /></button></div>
      </div>
    </div>
  );
}

function MobileNav({ page, navigate, onCreate }: { page: Page; navigate: (page: Page) => void; onCreate: () => void }) {
  return (
    <nav className="mobile-nav">
      <button className={page.type === 'home' ? 'active' : ''} onClick={() => navigate({ type: 'home' })}><Home /><span>Home</span></button>
      <button className={page.type === 'explore' ? 'active' : ''} onClick={() => navigate({ type: 'explore' })}><Compass /><span>Discover</span></button>
      <button className="mobile-create" onClick={onCreate}><Plus /></button>
      <button className={page.type === 'saved' ? 'active' : ''} onClick={() => navigate({ type: 'saved' })}><Bookmark /><span>Saved</span></button>
      <button className={page.type === 'profile' ? 'active' : ''} onClick={() => navigate({ type: 'profile' })}><User /><span>Profile</span></button>
    </nav>
  );
}

/* ------------------------------------------------------------------ */
/* App                                                                 */
/* ------------------------------------------------------------------ */

function readStored<T>(key: string, fallback: T): T {
  try {
    const value = localStorage.getItem(key);
    return value ? JSON.parse(value) as T : fallback;
  } catch {
    return fallback;
  }
}

interface PendingCreate {
  name: string;
  stage: CreateStage;
  detail: string;
  error?: string;
}

function App() {
  const [page, setPage] = useState<Page>({ type: 'home' });
  const [sort, setSort] = useState<SortOption>('Best');
  const [communityList, setCommunityList] = useState<CommunityProfile[]>(() => registry.all());
  const [allPosts, setAllPosts] = useState<Post[]>(() => seedPosts.map(post => ({
    ...post,
    generated: true,
    generator: 'engine' as const,
    ageMinutes: post.time.includes('m') ? parseInt(post.time) : post.time.includes('h') ? parseInt(post.time) * 60 : 1440,
    contextSource: 'builtin' as const,
  })));
  const [contexts, setContexts] = useState<Record<string, CultureProfile>>({});
  const [contextErrors, setContextErrors] = useState<Record<string, string>>({});
  const [refreshing, setRefreshing] = useState<Record<string, boolean>>({});
  const [pending, setPending] = useState<Record<string, PendingCreate>>({});
  const [votes, setVotes] = useState<Record<string, VoteState>>(() => readStored('fora-votes', {}));
  const [saved, setSaved] = useState<Set<string>>(() => new Set(readStored<string[]>('fora-saved', [])));
  const [subscribed, setSubscribed] = useState<Set<string>>(() => new Set(
    readStored<string[]>('fora-subscribed-v2', builtinCommunities.filter(c => c.subscribed).map(c => c.id)),
  ));
  const [theme, setThemeState] = useState<'light' | 'dark'>(() => (localStorage.getItem('fora-theme') as 'light' | 'dark') || 'light');
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [toast, setToast] = useState('');
  const homeBatch = useRef(0);
  const communityBatch = useRef<Record<string, number>>({});
  const seeded = useRef<Set<string>>(new Set());
  const contextRequested = useRef<Set<string>>(new Set());

  const notify = useCallback((message: string) => {
    setToast(message);
    window.setTimeout(() => setToast(''), 3200);
  }, []);

  const navigate = useCallback((next: Page) => {
    setPage(next);
    setSidebarOpen(false);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  const setTheme = (next: 'light' | 'dark') => { setThemeState(next); localStorage.setItem('fora-theme', next); };

  const communityFor = useCallback(
    (id: string) => communityList.find(item => item.id === id) || registry.get(id) || fallbackCommunity(id),
    [communityList],
  );

  useEffect(() => registry.subscribe(() => setCommunityList(registry.all())), []);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { localStorage.setItem('fora-votes', JSON.stringify(votes)); }, [votes]);
  useEffect(() => { localStorage.setItem('fora-saved', JSON.stringify(Array.from(saved))); }, [saved]);
  useEffect(() => { localStorage.setItem('fora-subscribed-v2', JSON.stringify(Array.from(subscribed))); }, [subscribed]);
  useEffect(() => {
    const handler = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault();
        (document.querySelector('.searchbar input') as HTMLInputElement)?.focus();
      }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, []);

  /* ---- context loading ------------------------------------------- */

  const syncContext = useCallback(async (community: CommunityProfile, force = false) => {
    const key = community.sourceSubreddit || community.id;
    if (!force && contextRequested.current.has(key)) return;
    contextRequested.current.add(key);
    setRefreshing(current => ({ ...current, [community.id]: true }));
    const before = contexts[community.id]?.source;
    const { profile, error } = await loadContext(community, { force });
    setContexts(current => ({ ...current, [community.id]: profile }));
    setContextErrors(current => ({ ...current, [community.id]: error || '' }));
    setRefreshing(current => ({ ...current, [community.id]: false }));
    if (profile.source === 'live') {
      registry.upsert({ ...community, members: profile.subscribers || community.members, online: profile.activeUsers || community.online });
      if (before && before !== 'live') {
        resetLedger(community.id);
        communityBatch.current[community.id] = 0;
        seeded.current.delete(community.id);
        setAllPosts(current => current.filter(post => post.communityId !== community.id || post.generator === 'you'));
        notify(`Live context synced for ${community.name} — regenerating feed`);
      }
    } else if (error && force) {
      notify(error);
    }
  }, [contexts, notify]);

  /* ---- generation -------------------------------------------------- */

  const seedCommunityFeed = useCallback(async (community: CommunityProfile) => {
    if (seeded.current.has(community.id)) return;
    seeded.current.add(community.id);
    const profile = contexts[community.id] || getContextSync(community);
    setContexts(current => (current[community.id] ? current : { ...current, [community.id]: profile }));
    const result = await generateBatch(community, { count: 7, batch: 0, profile });
    communityBatch.current[community.id] = 1;
    setAllPosts(current => {
      const existing = new Set(current.map(post => post.id));
      return [...result.posts.filter(post => !existing.has(post.id)), ...current];
    });
    if (result.modelError) notify(`Model unavailable (${result.modelError}) — using the built-in engine`);
  }, [contexts, notify]);

  const loadMoreCommunity = useCallback(async (community: CommunityProfile) => {
    setLoadingMore(true);
    try {
      const batch = communityBatch.current[community.id] ?? 1;
      communityBatch.current[community.id] = batch + 1;
      const profile = contexts[community.id] || getContextSync(community);
      const result = await generateBatch(community, { count: 6, batch, profile });
      setAllPosts(current => {
        const existing = new Set(current.map(post => post.id));
        return [...current, ...result.posts.filter(post => !existing.has(post.id))];
      });
    } finally {
      setLoadingMore(false);
    }
  }, [contexts]);

  const loadMoreHome = useCallback(async () => {
    const ids = Array.from(subscribed);
    if (!ids.length) return;
    setLoadingMore(true);
    try {
      const batch = homeBatch.current;
      homeBatch.current += 1;
      const posts = await generateHomeBatch(ids, batch, 6);
      setAllPosts(current => {
        const existing = new Set(current.map(post => post.id));
        return [...current, ...posts.filter(post => !existing.has(post.id))];
      });
    } finally {
      setLoadingMore(false);
    }
  }, [subscribed]);

  /* ---- simulate a subreddit ---------------------------------------- */

  const simulate = useCallback(async (rawName: string) => {
    const slug = normalizeSubredditName(rawName);
    if (!slug) {
      notify('Enter a subreddit name');
      return;
    }
    const id = slug.toLowerCase();
    const existing = registry.get(id);
    navigate({ type: 'community', id });
    if (existing) {
      syncContext(existing);
      seedCommunityFeed(existing);
      return;
    }

    setPending(current => ({ ...current, [id]: { name: slug, stage: 'lookup', detail: `Looking up r/${slug}` } }));
    try {
      const result = await createCommunity(slug, (stage, detail) => {
        setPending(current => ({ ...current, [id]: { name: slug, stage, detail: detail || '' } }));
      });
      setContexts(current => ({ ...current, [id]: result.profile }));
      setContextErrors(current => ({ ...current, [id]: result.warning || '' }));
      contextRequested.current.add(result.community.sourceSubreddit || id);
      seeded.current.add(id);
      const batch = await generateBatch(result.community, { count: 8, batch: 0, profile: result.profile });
      communityBatch.current[id] = 1;
      setAllPosts(current => [...batch.posts, ...current]);
      setPending(current => {
        const next = { ...current };
        delete next[id];
        return next;
      });
      setSubscribed(current => new Set(current).add(id));
      if (result.warning) notify(`r/${slug} simulated from an estimated profile — ${result.warning}`);
      else notify(`r/${slug} simulated from ${result.profile.sampleSize} live signals`);
    } catch (error) {
      const message = error instanceof ContextUnavailableError
        ? error.message
        : error instanceof Error ? error.message : 'Something went wrong';
      setPending(current => ({ ...current, [id]: { name: slug, stage: 'lookup', detail: '', error: message } }));
    }
  }, [navigate, notify, seedCommunityFeed, syncContext]);

  /* ---- page effects ------------------------------------------------- */

  useEffect(() => {
    const timer = window.setTimeout(() => setLoading(false), 500);
    return () => window.clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (page.type !== 'community') return;
    const community = registry.get(page.id);
    if (!community) return;
    syncContext(community);
    seedCommunityFeed(community);
  }, [page, syncContext, seedCommunityFeed]);

  useEffect(() => {
    if (page.type !== 'home' || loading) return;
    const ids = Array.from(subscribed).slice(0, 5);
    for (const id of ids) {
      const community = registry.get(id);
      if (community) seedCommunityFeed(community);
    }
  }, [page.type, loading, subscribed, seedCommunityFeed]);

  /* ---- interactions ------------------------------------------------- */

  const toggleSubscribe = (id: string) => setSubscribed(current => {
    const next = new Set(current);
    const joining = !next.has(id);
    if (joining) next.add(id);
    else next.delete(id);
    notify(joining ? `Joined ${communityFor(id).name}` : `Left ${communityFor(id).name}`);
    return next;
  });

  const toggleSaved = (id: string) => setSaved(current => {
    const next = new Set(current);
    const saving = !next.has(id);
    if (saving) next.add(id);
    else next.delete(id);
    notify(saving ? 'Saved for later' : 'Removed from saved');
    return next;
  });

  const setVote = (id: string, value: VoteState) => setVotes(current => ({ ...current, [id]: value }));
  const findPost = (id: string) => allPosts.find(post => post.id === id);

  const updateCommentTree = (comments: Comment[], parentId: string, reply: Comment): Comment[] =>
    comments.map(comment => comment.id === parentId
      ? { ...comment, replies: [...(comment.replies || []), reply] }
      : { ...comment, replies: comment.replies ? updateCommentTree(comment.replies, parentId, reply) : [] });

  const replyTo = (postId: string, parentId: string, text: string) => setAllPosts(current => current.map(post =>
    post.id === postId
      ? {
        ...post,
        comments: post.comments + 1,
        commentTree: updateCommentTree(post.commentTree || [], parentId, {
          id: `reply-${Date.now()}`, author: currentUser.name, avatar: currentUser.avatar, body: text, score: 1, time: 'now', replies: [],
        }),
      }
      : post));

  const addComment = (postId: string, text: string) => setAllPosts(current => current.map(post =>
    post.id === postId
      ? {
        ...post,
        comments: post.comments + 1,
        commentTree: [
          { id: `comment-${Date.now()}`, author: currentUser.name, avatar: currentUser.avatar, body: text, score: 1, time: 'now', replies: [] },
          ...(post.commentTree || []),
        ],
      }
      : post));

  const clearCache = () => {
    try {
      const keys = Object.keys(localStorage).filter(key => key.startsWith('fora-ctx-v2'));
      for (const key of keys) localStorage.removeItem(key);
    } catch {
      /* ignore */
    }
    contextRequested.current.clear();
    setContexts({});
    notify('Cached context cleared');
  };

  /* ---- derived ------------------------------------------------------ */

  const trending = useMemo(() => {
    const items: { label: string; community: CommunityProfile; momentum: string; heat: number }[] = [];
    for (const [id, profile] of Object.entries(contexts)) {
      const community = communityFor(id);
      for (const topic of profile.topics.slice(0, 3)) {
        items.push({ label: topic.label, community, momentum: `${topic.kind} · ${topic.momentum}`, heat: topic.heat * (topic.momentum === 'rising' ? 1.4 : 1) });
      }
    }
    return items.sort((a, b) => b.heat - a.heat).slice(0, 6);
  }, [contexts, communityFor]);

  const homePosts = useMemo(
    () => sortPosts(allPosts.filter(post => subscribed.has(post.communityId)), sort),
    [allPosts, subscribed, sort],
  );

  const activeCommunity = page.type === 'community' ? registry.get(page.id) : undefined;
  const communityPosts = useMemo(
    () => (activeCommunity ? sortPosts(allPosts.filter(post => post.communityId === activeCommunity.id), sort) : []),
    [allPosts, activeCommunity, sort],
  );

  const homeSentinel = useInfiniteScroll(loadMoreHome, page.type === 'home' && !loading, `home-${subscribed.size}`);
  const communitySentinel = useInfiniteScroll(
    async () => { if (activeCommunity) await loadMoreCommunity(activeCommunity); },
    page.type === 'community' && Boolean(activeCommunity),
    `community-${activeCommunity?.id || 'none'}`,
  );

  const feedShared = {
    sort,
    setSort,
    navigate,
    votes,
    setVote,
    saved,
    toggleSaved,
    notify,
    communityFor,
  };

  let content: ReactNode;
  if (page.type === 'home') {
    content = (
      <HomePage
        {...feedShared}
        posts={homePosts}
        subscribed={subscribed}
        toggleSubscribe={toggleSubscribe}
        loading={loading}
        loadingMore={loadingMore}
        sentinelRef={homeSentinel}
        communities={communityList}
        onSimulate={simulate}
        trending={trending}
      />
    );
  } else if (page.type === 'explore') {
    content = <ExplorePage navigate={navigate} subscribed={subscribed} toggleSubscribe={toggleSubscribe} communities={communityList} onSimulate={simulate} />;
  } else if (page.type === 'community') {
    const pendingState = pending[page.id];
    if (!activeCommunity && pendingState) {
      content = (
        <CreatingView
          name={pendingState.name}
          stage={pendingState.stage}
          detail={pendingState.detail}
          error={pendingState.error}
          onRetry={() => simulate(pendingState.name)}
          onHome={() => navigate({ type: 'home' })}
        />
      );
    } else if (!activeCommunity) {
      content = (
        <EmptyState
          icon={<Compass />}
          title={`r/${page.id} is not simulated yet`}
          text="Generate this community from its real counterpart."
          action="Simulate it"
          onAction={() => simulate(page.id)}
        />
      );
    } else {
      content = (
        <CommunityPage
          {...feedShared}
          community={activeCommunity}
          posts={communityPosts}
          subscribed={subscribed}
          toggleSubscribe={toggleSubscribe}
          loading={loading && !communityPosts.length}
          loadingMore={loadingMore}
          sentinelRef={communitySentinel}
          profile={contexts[activeCommunity.id]}
          refreshing={Boolean(refreshing[activeCommunity.id])}
          onRefresh={() => syncContext(activeCommunity, true)}
          contextError={contextErrors[activeCommunity.id] || undefined}
        />
      );
    }
  } else if (page.type === 'post') {
    const post = findPost(page.id);
    content = post
      ? (
        <PostDetail
          post={post}
          community={communityFor(post.communityId)}
          navigate={navigate}
          vote={votes[post.id] || null}
          onVote={value => setVote(post.id, value)}
          saved={saved.has(post.id)}
          onSave={() => toggleSaved(post.id)}
          notify={notify}
          onComment={text => addComment(post.id, text)}
          onReply={(parentId, text) => { replyTo(post.id, parentId, text); notify('Reply posted'); }}
          subscribed={subscribed}
          toggleSubscribe={toggleSubscribe}
        />
      )
      : <EmptyState icon={<FileText />} title="Post not found" text="This thread is no longer in memory." action="Back home" onAction={() => navigate({ type: 'home' })} />;
  } else if (page.type === 'saved') {
    content = <SavedPage {...feedShared} posts={allPosts.filter(post => saved.has(post.id))} />;
  } else if (page.type === 'search') {
    content = (
      <SearchPage
        query={page.query}
        posts={allPosts}
        navigate={navigate}
        communities={communityList}
        onSimulate={simulate}
        communityFor={communityFor}
        votes={votes}
        setVote={setVote}
        saved={saved}
        toggleSaved={toggleSaved}
        notify={notify}
        sort={sort}
        setSort={setSort}
      />
    );
  } else if (page.type === 'profile') {
    content = <ProfilePage navigate={navigate} posts={allPosts} communityFor={communityFor} />;
  } else {
    content = <SettingsPage theme={theme} setTheme={setTheme} notify={notify} onClearCache={clearCache} />;
  }

  return (
    <div className="app-shell">
      <Header
        page={page}
        navigate={navigate}
        onCreate={() => setCreateOpen(true)}
        theme={theme}
        setTheme={setTheme}
        sidebarOpen={sidebarOpen}
        setSidebarOpen={setSidebarOpen}
        notify={notify}
        communities={communityList}
        onSimulate={simulate}
      />
      <Sidebar page={page} navigate={navigate} subscribed={subscribed} open={sidebarOpen} setOpen={setSidebarOpen} communities={communityList} />
      <div className="content-shell">{content}</div>
      <MobileNav page={page} navigate={navigate} onCreate={() => setCreateOpen(true)} />
      <CreatePostModal
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        subscribed={subscribed}
        communities={communityList}
        onPublish={post => { setAllPosts(current => [post, ...current]); navigate({ type: 'post', id: post.id }); notify('Your post is live in the simulation'); }}
      />
      <div className={`toast ${toast ? 'show' : ''}`}><Check size={16} /> {toast}</div>
    </div>
  );
}

export default App;
